package review

import (
	"fmt"
	"strings"
	"time"
)

type CreateResponse struct {
	ReviewID     string
	Status       string
	FriendlyName string
}

type Response struct {
	Status  string
	Summary string
}

func IsFakeReviewBuild(mode string) bool {
	return strings.EqualFold(strings.TrimSpace(mode), "fake")
}

func FakeReviewWaitDuration(raw string) (time.Duration, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return 30 * time.Second, nil
	}

	d, err := time.ParseDuration(raw)
	if err != nil {
		return 0, fmt.Errorf("invalid LRC_FAKE_REVIEW_WAIT %q: %w", raw, err)
	}
	if d <= 0 {
		return 0, fmt.Errorf("LRC_FAKE_REVIEW_WAIT must be > 0, got %q", raw)
	}
	return d, nil
}

func BuildFakeSubmitResponse(now time.Time, friendlyName string) CreateResponse {
	ts := now.UnixNano()
	return CreateResponse{
		ReviewID:     fmt.Sprintf("fake-%d", ts),
		Status:       "queued",
		FriendlyName: friendlyName,
	}
}

func BuildFakeCompletedResult() *Response {
	return &Response{
		Status:  "completed",
		Summary: "# Fake Review Summary\n\nThis is a fake review generated by `build-local-test` for end-to-end testing.\n\n- No AI request was sent\n- Review data is synthetic and deterministic",
	}
}
